import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SidebarLayouts from "./sidebarLayouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* sidebar */}
        <main className="w-full flex">
          <section
            className={cn(
              "sticky top-0  h-screen xl:w-60 sm:w-[4.5rem] ",
              "bg-white dark:bg-black border border-gray-400"
            )}
          ></section>
          <section className="w-full xl:basis-4/5 ">{children}</section>
        </main>
      </body>
    </html>
  );
}
