import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SidebarLayouts from "./sidebarLayouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* sidebar */}
        <main className="w-full flex ">
          <SidebarLayouts />
          <section className="w-full">{children}</section>
        </main>
      </body>
    </html>
  );
}
