import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarLayouts from "./sidebarLayouts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* sidebar */}
        <main className="w-full flex">

          <SidebarLayouts />
          <section className="w-full xl:basis-4/5 ">{children}</section>
        </main>
      </body>
    </html>
  );
}
